# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_slugfield_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='resale_certificate',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
