# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_basket_resale_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='resale_certificate',
            field=models.FileField(upload_to=b'uploads/'),
        ),
    ]
