# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0004_auto_20160107_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from=b'name', unique=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
                ('partner_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('users', models.ManyToManyField(blank=True, related_name='_attributeemail_users_+', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'ordering': ('name', 'code'),
                'abstract': False,
                'verbose_name_plural': 'Fulfillment partners',
                'verbose_name': 'Fulfillment partner',
                'permissions': (('dashboard_access', 'Can access dashboard'),),
            },
        ),
    ]
