# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20171031_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeemail',
            name='users',
        ),
        migrations.DeleteModel(
            name='AttributeEmail',
        ),
    ]
