# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_resale_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='resale_certificate',
        ),
    ]
