# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170609_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'images/products/%Y/%m/', verbose_name='Image'),
        ),
    ]
